# Build from github package
services:
  server:
    container_name: DisasterAPI
    image: ghcr.io/echelon35/disasterapi:latest
    env_file:
      - ./.env.prod
    environment:
      NODE_ENV: production
    ports:
      - 4002:4002