# 
services:
  server:
    container_name: DisasterAPI
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    ports:
      - 4002:4002
